<?php
/**
 * @file
 * Code for the Stanford CAP API feature.
 */

include_once 'stanford_cap_api.features.inc';

/**
 * Implements hook_menu().
 */
function stanford_cap_api_menu() {
  $items = array();

  $items['admin/config/cap'] = array(
    'title' => 'Community Academic Profiles',
    'description' => 'Community Academic Profiles API screens.',
    'position' => 'right',
    'weight' => -5,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  $items['admin/config/cap/details'] = array(
    'title' => 'Details',
    'description' => "Displays information about the site's connection to the CAP API.",
    'page callback' => 'drupal_get_form',
    'page arguments' => array('stanford_cap_api_details_form'),
    // @todo Proper access check.
    'access callback' => TRUE,
    'weight' => -10,
    'file' => 'stanford_cap_api.admin.inc',
  );

  $items['admin/config/cap/settings'] = array(
    'title' => 'Settings',
    'description' => 'Provides administrators ability to change CAP API access settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('stanford_cap_api_settings_form'),
    // @todo Proper access check.
    'access callback' => TRUE,
    'weight' => 10,
    'file' => 'stanford_cap_api.admin.inc',
  );

  $items['admin/config/cap/import'] = array(
    'title' => 'Import profiles',
    'description' => 'Provides administrators ability to import CAP profiles.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('stanford_cap_api_import_form'),
    // @todo Proper access check.
    'access callback' => TRUE,
    'weight' => 5,
    'file' => 'stanford_cap_api.admin.inc',
  );

  $items['admin/config/cap/import/result'] = array(
    'title' => 'Import profiles',
    'description' => 'Provides administrators ability to import CAP profiles.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('stanford_cap_api_import_result_form'),
    // @todo Proper access check.
    'access callback' => TRUE,
    'file' => 'stanford_cap_api.admin.inc',
  );

  $items['admin/config/cap/profile_test'] = array(
    'title' => 'Faculty Profile Structure Synchronization',
    'description' => 'Faculty Profile Structure Synchronization',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('stanford_cap_api_profile_test'),
    // @todo Proper access check.
    'access callback' => TRUE,
    'file' => 'stanford_cap_api.admin.inc',
  );

  $items['admin/config/cap/manage'] = array(
    'title' => 'Manage profiles',
    'description' => 'Provides administrators ability to manage CAP profiles.',
    'page callback' => 'stanford_cap_api_manage',
    // @todo Proper access check.
    'access callback' => TRUE,
    'weight' => 6,
    'file' => 'stanford_cap_api.admin.inc',
  );

  return $items;
}

function stanford_cap_api_synchronize_fields($fields) {
  foreach ($fields as $field_name => $field_info) {
    $field_name = 'cap_' . $field_name;
    $info = field_info_field($field_name);
    // Field not exists yet.
    if (empty($info)) {
      $info = _cap_api_get_field_base_def($field_info['type'], $field_name);
      // Do we know about this field type?
      if (!empty($info)) {
        field_create_field($info);
        // Logging field creation.
        _cap_api_log_field($field_name);
        $info_instance = field_info_instance('node', $field_name, 'cap_faculty_profile');
        if (empty($info_instance)) {
          $instance = _cap_api_get_field_instance_def($field_info['type'], $field_name, $field_info['label']);
          field_create_instance($instance);
        }
      }
    }
  }
}

function _cap_api_get_field_base_def($type, $name) {
  $info = FALSE;
  switch ($type) {
    case 'link':
      $info = array(
        'active' => 1,
        'cardinality' => 1,
        'deleted' => 0,
        'entity_types' => array(),
        'field_name' => $name,
        'foreign keys' => array(),
        'indexes' => array(),
        'locked' => 0,
        'module' => 'link',
        'settings' => array(
          'attributes' => array(
            'class' => '',
            'rel' => '',
            'target' => 'default',
          ),
          'display' => array(
            'url_cutoff' => 80,
          ),
          'enable_tokens' => 1,
          'title' => 'optional',
          'title_maxlength' => 128,
          'title_value' => '',
          'url' => 0,
        ),
        'translatable' => 0,
        'type' => 'link_field',
      );
      break;

    case 'date':
      $info = array(
        'active' => 1,
        'cardinality' => 1,
        'deleted' => 0,
        'entity_types' => array(),
        'field_name' => $name,
        'foreign keys' => array(),
        'indexes' => array(),
        'locked' => 0,
        'module' => 'date',
        'settings' => array(
          'cache_count' => 4,
          'cache_enabled' => 0,
          'granularity' => array(
            'day' => 'day',
            'hour' => 0,
            'minute' => 0,
            'month' => 'month',
            'second' => 0,
            'year' => 'year',
          ),
          'timezone_db' => '',
          'todate' => '',
          'tz_handling' => 'none',
        ),
        'translatable' => 0,
        'type' => 'datestamp',
      );
      break;

    case 'string':
      $info = array(
        'active' => 1,
        'cardinality' => 1,
        'deleted' => 0,
        'entity_types' => array(),
        'field_name' => $name,
        'foreign keys' => array(
          'format' => array(
            'columns' => array(
              'format' => 'format',
            ),
            'table' => 'filter_format',
          ),
        ),
        'indexes' => array(
          'format' => array(
            0 => 'format',
          ),
        ),
        'locked' => 0,
        'module' => 'text',
        'settings' => array(
          'max_length' => 255,
        ),
        'translatable' => 0,
        'type' => 'text',
      );
      break;

    case 'text':
      $info = array(
        'active' => 1,
        'cardinality' => 1,
        'deleted' => 0,
        'entity_types' => array(),
        'field_name' => $name,
        'foreign keys' => array(
          'format' => array(
            'columns' => array(
              'format' => 'format',
            ),
            'table' => 'filter_format',
          ),
        ),
        'indexes' => array(
          'format' => array(
            0 => 'format',
          ),
        ),
        'locked' => 0,
        'module' => 'text',
        'settings' => array(),
        'translatable' => 0,
        'type' => 'text_long',
      );
      break;
  }

  return $info;
}

function _cap_api_get_field_instance_def($type, $name, $label) {
  $info = FALSE;
  $label = check_plain($label);
  switch ($type) {
    case 'link':
      $info = array(
        'bundle' => 'cap_faculty_profile',
        'default_value' => NULL,
        'deleted' => 0,
        'description' => '',
        'display' => array(
          'default' => array(
            'label' => 'above',
            'module' => 'link',
            'settings' => array(),
            'type' => 'link_default',
            'weight' => 4,
          ),
          'teaser' => array(
            'label' => 'above',
            'settings' => array(),
            'type' => 'hidden',
            'weight' => 0,
          ),
        ),
        'entity_type' => 'node',
        'field_name' => $name,
        'label' => $label,
        'required' => 0,
        'settings' => array(
          'attributes' => array(
            'class' => '',
            'configurable_title' => 0,
            'rel' => '',
            'target' => 'default',
            'title' => '',
          ),
          'display' => array(
            'url_cutoff' => 80,
          ),
          'enable_tokens' => 1,
          'rel_remove' => 'default',
          'title' => 'none',
          'title_maxlength' => 128,
          'title_value' => '',
          'url' => 0,
          'user_register_form' => FALSE,
          'validate_url' => 1,
        ),
        'widget' => array(
          'active' => 0,
          'module' => 'link',
          'settings' => array(),
          'type' => 'link_field',
          'weight' => 44,
        ),
      );
      break;

    case 'date':
      $info = array(
        'bundle' => 'cap_faculty_profile',
        'default_value' => NULL,
        'deleted' => 0,
        'description' => '',
        'display' => array(
          'default' => array(
            'label' => 'above',
            'module' => 'date',
            'settings' => array(
              'format_type' => 'long',
              'fromto' => 'both',
              'multiple_from' => '',
              'multiple_number' => '',
              'multiple_to' => '',
            ),
            'type' => 'date_default',
            'weight' => 1,
          ),
          'stanford_cap_instructor' => array(
            'label' => 'above',
            'settings' => array(),
            'type' => 'hidden',
            'weight' => 0,
          ),
          'teaser' => array(
            'label' => 'above',
            'settings' => array(),
            'type' => 'hidden',
            'weight' => 0,
          ),
        ),
        'entity_type' => 'node',
        'field_name' => $name,
        'label' => $label,
        'required' => 0,
        'settings' => array(
          'default_value' => 'now',
          'default_value2' => 'same',
          'default_value_code' => '',
          'default_value_code2' => '',
          'user_register_form' => FALSE,
        ),
        'widget' => array(
          'active' => 1,
          'module' => 'date',
          'settings' => array(
            'display_all_day' => 0,
            'increment' => 15,
            'input_format' => 'm/d/Y - H:i:s',
            'input_format_custom' => '',
            'label_position' => 'above',
            'text_parts' => array(),
            'year_range' => '-3:+3',
          ),
          'type' => 'date_select',
          'weight' => 41,
        ),
      );
      break;

    case 'string':
      $info = array(
        'bundle' => 'cap_faculty_profile',
        'default_value' => NULL,
        'deleted' => 0,
        'description' => '',
        'display' => array(
          'default' => array(
            'label' => 'above',
            'module' => 'text',
            'settings' => array(),
            'type' => 'text_default',
            'weight' => 2,
          ),
          'teaser' => array(
            'label' => 'above',
            'settings' => array(),
            'type' => 'hidden',
            'weight' => 0,
          ),
        ),
        'entity_type' => 'node',
        'field_name' => $name,
        'label' => $label,
        'required' => 0,
        'settings' => array(
          'text_processing' => 0,
          'user_register_form' => FALSE,
        ),
        'widget' => array(
          'active' => 1,
          'module' => 'text',
          'settings' => array(
            'size' => 60,
          ),
          'type' => 'text_textfield',
          'weight' => 42,
        ),
      );
      break;

    case 'text':
      $info = array(
        'bundle' => 'cap_faculty_profile',
        'default_value' => NULL,
        'deleted' => 0,
        'description' => '',
        'display' => array(
          'default' => array(
            'label' => 'above',
            'module' => 'text',
            'settings' => array(),
            'type' => 'text_default',
            'weight' => 5,
          ),
          'teaser' => array(
            'label' => 'above',
            'settings' => array(),
            'type' => 'hidden',
            'weight' => 0,
          ),
        ),
        'entity_type' => 'node',
        'field_name' => $name,
        'label' => $label,
        'required' => 0,
        'settings' => array(
          'text_processing' => 0,
          'user_register_form' => FALSE,
        ),
        'widget' => array(
          'active' => 1,
          'module' => 'text',
          'settings' => array(
            'rows' => 5,
          ),
          'type' => 'text_textarea',
          'weight' => 45,
        ),
      );
      break;
  }

  return $info;
}

function _cap_api_log_field($field_name) {
  $record = array('field_name' => $field_name);
  drupal_write_record('cap_api_fields', $record);
  watchdog('stanford_cap_api', 'Field @field was created by stanford_cap_api module.', array('@field' => $field_name));
}

/**
 * Implements hook_menu_alter().
 */
function stanford_cap_api_menu_alter(&$items) {
  $items['node/%node/edit']['access callback'] = 'stanford_cap_api_node_access';
  $items['admin/structure/types/manage/%node_type/fields']['access callback'] = 'stanford_cap_api_user_access';
  $items['admin/structure/types/manage/%node_type/fields']['access arguments'][] = 4;
}

/**
 * Access check callback.
 */
function stanford_cap_api_node_access($op, $node) {
  $access = node_access($op, $node);
  if ($access && $node->type == 'cap_faculty_profile') {
    if (!variable_get('cap_allow_edit', FALSE)) {
      $access = FALSE;
    }
  }

  return $access;
}

/**
 * Access check callback.
 */
function stanford_cap_api_user_access($permission, $node_type) {
  $access = user_access($permission);
  if ($access && $node_type->type == 'cap_faculty_profile') {
    if (!variable_get('cap_custom_fields', FALSE)) {
      $access = FALSE;
    }
  }

  return $access;
}

/**
 * Authenticate with CAP and reutrn an authentication token.
 *
 * @return string
 *   An authentication token that can be used for API calls
 */
function stanford_cap_api_auth() {

  $auth_uri = variable_get('cap_auth_uri', 'https://authz-test.stanford.edu/oauth/token');
  $user = variable_get('cap_username', '');
  $pass = variable_get('cap_password', '');

  $params = array(
    'grant_type' => 'client_credentials',
    'scope' => 'profiles.read_public',
  );

  if (empty($user) || empty($pass)) {
    return FALSE;
  }

  // Append user/pass, some system doesn't support http_build_url.
  $uri = parse_url($auth_uri);

  $host = $user . ':' . $pass . '@' . $uri['host'];
  $auth_url = str_replace($uri['host'], $host, $auth_uri);

  $auth_url = url($auth_url, array('query' => $params, 'external' => TRUE));
  $response = drupal_http_request($auth_url);
  // Error could be here as well.
  if (property_exists($response, 'error')) {
    $error_msg = 'Failed to fetch data from CAP API service. Error code is'
      . ' %code, error message is "%msg", request string was "%request".';
    $vars = array(
      '%code' => $response->code,
      '%msg' => $response->status_message,
      '%request' => $response->request,
    );
    watchdog('stanford_cap_api', $error_msg, $vars, WATCHDOG_WARNING);

    return FALSE;
  }

  // Log bad API authentication.
  $data = json_decode($response->data, TRUE);
  if (array_key_exists('error', $data)) {
    $error_msg = 'Error found in CAP API response. Error message is "%msg",'
      . ' response data was "%data".';
    $vars = array(
      '%msg' => $data['error_description'],
      '%data' => print_r($data, TRUE),
    );
    watchdog('stanford_cap_api', $error_msg, $vars, WATCHDOG_WARNING);

    return FALSE;
  }

  // Authentication successful, return the access token.
  if (array_key_exists('access_token', $data)) {
    return $data['access_token'];
  }

  return FALSE;
}

/**
 * Issue an API call against an API endpoint.
 */
function stanford_cap_api_request($endpoint, $params = array()) {
  // Real endpoint is "http://irt-dev.stanford.edu/cap-api"
  $api_base = variable_get('cap_api_base_url', 'http://irt-dev.stanford.edu/cap-api');

  $access_token = stanford_cap_api_auth();
  // Unable to fetch an auth token.
  if (!$access_token) {
    return FALSE;
  }

  $query = array(
    'access_token' => $access_token,
  );

  $request_url = url($api_base . $endpoint, array(
    'query' => $params += $query,
    'external' => TRUE,
  ));

  $response = drupal_http_request($request_url);
  // Error could be here as well.
  if (property_exists($response, 'error')) {
    $error_msg = 'Failed to fetch data from CAP API service. Error code is'
      . ' %code, error message is "%msg", request string was "%request".';
    $vars = array(
      '%code' => $response->code,
      '%msg' => $response->status_message,
      '%request' => $response->request,
    );
    watchdog('stanford_cap_api', $error_msg, $vars, WATCHDOG_WARNING);

    return FALSE;
  }

  // Log bad API authentication.
  $data = json_decode($response->data, TRUE);
  if (array_key_exists('error', $data)) {
    $error_msg = 'Error found in CAP API response. Error message is "%msg",'
     . ' response data was "%data".';
    $vars = array(
      '%msg' => $data['error_description'],
      '%data' => print_r($data, TRUE),
    );
    watchdog('stanford_cap_api', $error_msg, $vars, WATCHDOG_WARNING);

    return FALSE;
  }
  else {
    return $data;
  }
}

function stanford_cap_api_test() {
  $endpoint = '/api/cap/v1/orgs';
  $params = array('orgCodes' => 'VAAA');
//  $params = array('orgCodes' => 'VDAB');
//  AADW -President's Office Financials
//  $params = array('orgCodes' => 'AADW');
  $data = stanford_cap_api_request($endpoint, $params);
  dpm($data, 'Raw data');
  foreach ($data as $orgid => $organization) {
    stanford_cap_api_save_organization($organization, $orgid);
  }
}

/**
 * Save organization fetch from CAP API.
 *
 * @param array $organization
 *   Array containing organization description.
 * @param int $orgid
 *   Organization ID inside Stanford University. Could be 0 for root entry,
 * Stanford University itself.
 */
function stanford_cap_api_save_organization($organization, $orgid = 0) {
  $organization['orgid'] = $orgid;
  if (isset($organization['children'])) {
    $childrens = $organization['children'];
    $childrens_id = array();
    foreach ($childrens as $orgid => $org) {
      $childrens_id[] = $orgid;
      stanford_cap_api_save_organization($org, $orgid);
    }
    $organization['children'] = $childrens_id;
  }
  drupal_write_record('cap_api_orgs', $organization);
}

/**
 * Imports organizations from CAP API.
 *
 * Organizations have tree structure. To import them we must specify top level
 * organization code. This can be code of root entry - Stanford University(AA00)
 * itself, or code of one of departments, like School of Medicine(VAAA).
 *
 * @param string $top
 *   Top level organization code.
 */
function stanford_cap_api_import_organizations($top = 'AA00') {
  db_delete('cap_api_orgs')->execute();
  // Organizations endpoint.
  $endpoint = '/api/cap/v1/orgs';
  $params = array('orgCodes' => $top);
  $data = stanford_cap_api_request($endpoint, $params);
  dpm($data, 'Raw data');
  foreach ($data as $orgid => $organization) {
    stanford_cap_api_save_organization($organization, $orgid);
  }
}

/**
 * Implements hook_cron().
 */
function stanford_cap_api_cron() {
  $last_run_time = variable_get('stanford_cap_api_cron_last_run', REQUEST_TIME);
  $time_since_last_run = REQUEST_TIME - $last_run_time;
  // Check if last run wsa more then one day ago.
  if ($time_since_last_run > 86400) {
    stanford_cap_api_import_organizations();
  }
  variable_set('stanford_cap_api_cron_last_run', REQUEST_TIME);
}
